version: '3.3'
services:
  db:    
    environment:
      MYSQL_DATABASE: 'db_azsia'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'netrhal'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'worldpeace'
      # Set the prefered port
      MYSQL_TCP_PORT: 3308    
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3308:3308'
    expose:
      # Opens port 3308 on the container
      - '3308'